- hosts: webservers
  become: yes
  become_user: root
  tasks:
    - include: env-preparation-playbook.yml
    - include: nginx-playbook.yml
    - include: deploy-playbook.yml
  handlers:
    - include: nginx-handler.yml